# Data Analysis

## Plan of the module

1. Data Analysis
1. Data Sourcing
1. Data Visualization

## Lecture outline

- Jupyter (10 min)
- NumPy (30 min)
- pandas (50 min)

## Jupyter

> [...] is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text. Uses include: **data cleaning** and transformation, numerical simulation, statistical modeling, **data visualization**, machine learning, and much more.

👉 [Jupyter.org](https://jupyter.org/)

Open your terminal:

```bash
cd ~/some/where
jupyter notebook
```

Let's have a _quick tour_ !

## NumPy


> Fundamental package for high-performance data manipulation with Python

👉 [NumPy.org](https://www.numpy.org)

👉 [NumPy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) to print/bookmark

The key concept NumPy introduces is the **N-dimension Array** (ndarray)



**Characteristics of the ndarray:**

- it is **multidimensional**
- data is **homogenous**
- it has a **fixed size** defined upon creation

<img src='https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/numpy_array.png' width='600'>

In [9]:
import numpy as np # Canonical import

In [10]:
l = [[1,2,3], [4,5,6]]
print(type(l))
l # list of list

<class 'list'>

[[1, 2, 3], [4, 5, 6]]

In [11]:
A = np.array([[1,2,3], [4,5,6]])
print(type(A))
A # ndarray

<class 'numpy.ndarray'>

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# key Attributes of ndarrays
print('A.ndim: ', A.ndim)
print('A.shape:', A.shape)
print('A.size: ', A.size)
print('A.dtype:', A.dtype)

A.ndim:  2
A.shape: (2, 3)
A.size:  6
A.dtype: int64

### Data selection 😎

In [13]:
# lets build a 2D array from a list of list
data_list = [
    [ 0,  1,  2,  3,  4],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44],
]
data_np = np.array(data_list)
data_np

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

<img src='https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/numpy_slice1.png' width=200>

In [14]:
# Pure python
data_list[2][1:4]

[21, 22, 23]

In [15]:
# NumPy
data_np[2, 1:4] # data_np[row(s), column(s)]

array([21, 22, 23])

<img src='https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/numpy_slice2.png' width=200>

In [16]:
# Pure python
selection = []
for index, row in enumerate(data_list):
    if index > 0:
        selection.append(row[4])
selection # We could also have used a list comprehension for less lines

[14, 24, 34, 44]

In [17]:
# NumPy
data_np[1:, 4] # `1:` means from line 1 until the end.

array([14, 24, 34, 44])

### Slicing general syntax

```python
ndarray[start:stop:step]
```

In [18]:
A = np.arange(0, 10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
A[1:7:2]

array([1, 3, 5])

### Vectorized operations ⚡️

Let's compute the sum row-by-row (8 additions) to create a 1D vector

In [20]:
my_list = [
    [6, 5],
    [1, 3],
    [5, 6],
    [1, 4],
    [3, 7],
    [5, 8],
    [3, 5],
    [8, 4],
]

In [21]:
# Python way
sums = []
for row in my_list:
    sums.append(row[0] + row[1]) # standard integer "+" operator
sums

[11, 4, 11, 5, 10, 13, 8, 12]

### The NumPy way

<img src="https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/numpy_vectorized2.png" width="450">

In [22]:
A = np.array(my_list)
my_sum = A[:,0] + A[:,1] # Vectorial "+" operator
my_sum

array([11,  4, 11,  5, 10, 13,  8, 12])

### Axes 🤯
<img src='https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/numpy_axis.png' width=700>

**2D example**
```python
np.sum(A, axis=0)  # eq. to A[0,:] + A[1,:] + A[2,:] + ...
np.sum(A, axis=1)  # eq. to A[:,0] + A[:,1] + A[:,2] + ... 
```
<img src='https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/numpy_max_axis.png' width=600>

### How much faster is NumPy? ⚡️

In [23]:
# 2D ndarray of shape (10000, 10000) with random float in [0, 1] interval. That's 100M numbers!
A = np.random.rand(10000, 10000)
a = A.tolist()

In [24]:
%%time
total = 0
for row in a:
    for n in row:
        total += n
round(total, 2)

CPU times: user 5.49 s, sys: 317 ms, total: 5.81 s
Wall time: 5.85 s

50002380.97

In [25]:
%%time
round(np.sum(A), 2)

CPU times: user 72.1 ms, sys: 68.4 ms, total: 140 ms
Wall time: 145 ms

50002380.97

⚡️ NumPy is **two order of magnitude** faster!

### Boolean indexing 🔥

Build a **boolean mask** from a ndarray.

<img src="https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/numpy_boolean_index.png" width=600>

### Limits of NumPy

- Lack of support for **column names**
- **Only one** data type per ndarray
- Some useful data processing methods missing

👉 **Pandas** builds on NumPy to solve these problems

## Pandas Introduction


> [...] is an open source library providing high-performance easy-to-use data structures and data analysis tools for Python.

👉 [Pandas.pydata.org](https://pandas.pydata.org)

👉 [Pandas cheat sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) to print/bookmark

### pandas Series
- Pandas equivalent to numpy **1D ndarray** (accept same methods)
- with an additional index
- with support for multiple data types

👉 [pandas.Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html)

In [26]:
import pandas as pd

s = pd.Series(data=[1,2,'three'], index=['id1', 'id2', 'id3'])
s = pd.Series({'id1': 1, 'id2': 2, 'id3': 'three'})
s

id1        1
id2        2
id3    three
dtype: object

### pandas DataFrames

Pandas equivalent of a NumPy **2D ndarray** :
- with additional labels on both axes (row and columns)
- with multiple data types

👉 [pandas.DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)

<img src="https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/pandas_dataframe.png" width=600>

In [27]:
import pandas as pd

df = pd.DataFrame(
    [[4, 7, 10],
     [5, 8, 11],
     [6, 9, 12]],
    index=['row_1', 'row_2', 'row_3'],
    columns=["col_a", "col_b", "col_c"]
)
df

       col_a  col_b  col_c
row_1      4      7     10
row_2      5      8     11
row_3      6      9     12

### DataFrames are a dictionary of Series

<img src='https://wagon-public-datasets.s3.amazonaws.com/data-science-images/lectures/series-and-dataframe.png' width=300>

In [28]:
apples  = pd.Series(data=[1, 2, 3], index=["id1", "id2", "id3"])
oranges = pd.Series(data=[4, 5, 6], index=["id1", "id2", "id3"])
d = {
    "apples": apples,
    "oranges": oranges,
}
pd.DataFrame(d)

     apples  oranges
id1       1        4
id2       2        5
id3       3        6

## Exploratory Data Analysis


Starting a new notebook to explore a dataset: [Countries of the World](https://www.kaggle.com/fernandol/countries-of-the-world).

You can have a look at it [in this gist](https://gist.github.com/ssaunier/fcf6e1c9485f2d64607a093795372339) and download it with:

```bash
curl -s -L https://lew.ag/countries-dataset > countries.csv
head -n 3 countries.csv
```

This is how all Notebooks always start:

```python
import numpy as np
import pandas as pd
```

### Notebook Super Powers

In a new cell:

```python
pd.read<TAB>
```

```python
pd.read_csv<SHIFT+TAB> # (once, twice, three times or four times)
```

Go ahead and load the CSV into a `countries_df` DataFrame:

```python
file = "countries.csv" # Path relative to your notebook
countries_df = pd.read_csv(file, decimal=',')
```

### Get a quick sense of the data

Here are some utility methods to call on a fresh `DataFrame`:

```python
countries_df.shape # => Tuple representing the dimensionality of the DataFrame
```

Replace `.shape` with:

- [`pandas.DataFrame.dtypes`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dtypes.html)
- [`pandas.DataFrame.info()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html)
- [`pandas.DataFrame.describe()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html)

You can also do:

```python
countries_df.isnull().sum()
```

### Get a quick look

```python
countries_df.head()

countries_df.tail()
```

### Same logic as SQL!

You can manipulate a DataFrame the same way you query a relational database table.

👉 [Pandas Doc: Comparaison with SQL](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_sql.html)

### Reading column(s)

Use the `[]` syntax to get one or many columns:

```python
countries_df["Country"]

type(countries_df["Country"]) # => pandas.core.series.Series
```

```python
countries_df[["Country", "Region"]]

type(countries_df[["Country"]]) # => pandas.core.frame.DataFrame
```

### Group of rows/columns

```python
countries_df.loc[0:5, ["Country", "Region"]] # From row index 0 to 5 (included)
```

👉 After the lecture, read [this Stackoverflow Q&A thread](https://stackoverflow.com/questions/48409128/what-is-the-difference-between-using-loc-and-using-just-square-brackets-to-filte/48411543#48411543)

## Pandas - Boolean indexing

🤔 What are the countries with **more than one billion** inhabitants?

Pure Python naive implementation:

```python
big_countries = []
for index, country in countries_df.iterrows():
    if country['Population'] > 1_000_000_000:
        big_countries.append(country)
pd.DataFrame(big_countries)
```

This is a **one-liner** with **Boolean Indexing**:

```python
countries_df[countries_df["Population"] > 1_000_000_000]
```

🤔 What are the countries of the **American** continent?

```python
american = countries_df['Region'].str.contains('AMER')
countries_df[american]
```

🤔 What are the countries of **Europe**?

We can use [`pandas.Series.isin()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html#pandas.Series.isin)


```python
countries_df[countries_df["Region"].isin(["WESTERN EUROPE", "EASTERN EUROPE"])]
```

What happened?

```python
countries_df["Region"].unique()
```

We need to **cleanup** first:

```python
countries_df["Region"] = countries_df["Region"].str.strip()
```

If we want to answer the **inverse** question, we can use the bitwise oeprator `~`:

```python
countries_df[~countries_df["Region"].isin(["WESTERN EUROPE", "EASTERN EUROPE"])]
```

## Pandas - Re-indexing

```python
countries_df['Country'] = countries_df['Country'].map(str.strip)
countries_df.set_index('Country', inplace=True)
```

The index is no longer `0`, `1`, etc. but it's the country names!

We now can do something like this:

```python
countries_df.loc['France':'Germany', ['Region', 'Population']]
```

## Pandas - Sorting

We can sort on index with [`pandas.DataFrame.sort_index`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_index.html):

```python
countries_df.sort_index(ascending=False)
```

We can sort on columns with [`pandas.DataFrame.sort_values`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html):

```python
countries_df.sort_values(by='Population', ascending=False)
```

```python
countries_df.sort_values(by='GDP ($ per capita)', na_position='first')
```

## Pandas - Grouping

Very close to [`GROUP BY` in SQL](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_sql.html#group-by). It's a 3-step process:

1. **Split**: a DataFrame is split into groups depending on keys
2. **Apply**: an **aggregative** function (`sum`, `mean`, etc.) is applied on each group
3. **Combine**: result from the previous operations are merged (i.e. reduced) into one new DataFrame

🤔 Which region of the world is the most populated?

```python
regions = countries_df.groupby('Region')
```

```python
regions[['Population', 'Area (sq. mi.)']].sum()
```

```python
regions[['Population', 'Area (sq. mi.)']].sum() \
    .sort_values('Population', ascending=False)
```

## Plotting

```python
%matplotlib inline
import matplotlib
```

```python
gdp = 'GDP ($ per capita)'
top_ten_countries_df = countries_df[[gdp]] \
    .sort_values(gdp, ascending=False) \
    .head(10)

top_ten_countries_df
```

```python
top_ten_countries_df.plot(kind="bar")
```

## One more thing...

## Testing the notebooks

It is a bit different from how we have been testing the `py` files so far. 


💻 Let's take a look at the **first challenge** and see how you can check your results directly in the Notebook!

## Bibliography
- 📄 [Master NumPy arrays](https://towardsdatascience.com/here-are-30-ways-that-will-make-you-a-pro-at-creating-numpy-arrays-932b77d9a1eb)

## Your turn!